#!/bin/bash

. "${BASH_SOURCE[0]%/*}/../common"
. "${BASH_SOURCE[0]%/*}/common"
. "${scriptdir}/changelog"

_specfile="${pkgsrcdir}/${project}.spec"

_current_version="$(
	grep '^Version\:' "$_specfile" | sed 's/^Version\: *\([^ ]*\) *$/\1/'
)"
[ -z "$_current_version" ] && die "could not get current version"
version_greater "$version" "$_current_version" \
	|| die "accidental downgrade? new version ${version} <= ${_current_version}"

get_shortlog _changelog

update_rpm_version "$_specfile" "$version" "${_changelog:?bad changelog}"
