#!/bin/bash

. "${BASH_SOURCE[0]%/*}/../common"

get_output _output

_config="${PWD}/config.php"
echo "<? \$version = '$version';" > "$_config"
echo "\$is_snapshot = '$is_snapshot';" >> "$_config"
echo "\$outfile = '${_output##*/}';" >> "$_config"
echo "\$outdir = '$PWD';" >> "$_config"

get_output _source _sourcedir "$version" 'source'
e extract "$_source"
mv "$_sourcedir" "source"

get_output _build _builddir "$version" 'windows'
e extract "$_build"
mv "$_builddir" "build"

e preprocess_all "$_config" "${BASH_SOURCE[0]%/*}/common"
e preprocess_all "$_config" "${pkgsrcdir}"
e preprocess_all "$_config" "${pkgsrcdir}/lang" "lang"

WINEDEBUG=-all e wine "${BASH_SOURCE[0]%/*}/nsis/makensis.exe" \
	/V4 /INPUTCHARSET UTF8 /OUTPUTCHARSET UTF8 -- "${project}.nsi"

e mv "${_output##*/}" "$_output"
