#!/bin/bash

compiler="@compiler@"
root="@root@"
depsdir="@depsdir@"
PATH="@path@"

if [ ! -d "$depsdir" ] ; then
	exec "$compiler" "$@"
	exit 1
fi

depsfile="$(mktemp --tmpdir="$depsdir" XXXXXXXXXX)"

die() {
	echo "[wrapper] $@"
	exit 1
}

add_library_file() {
	if [ -f "$1" ] || [[ "$f" == /* ]]
		then echo "$(readlink -m -- "$1")" >> "$depsfile"
		else echo "$1" >> "$depsfile"
	fi
	
}

search_paths=( )

find_file() {
	[ ! -z "$file" ] && return
	for path in "${search_paths[@]}" ; do
		[ -f "${path}/${1}" ]       && file="${path}/${1}"         && return
	done
	if [ ! -z "$root" ] ; then
		[ -f "${root}/lib/${1}" ]     && file="${root}/lib/${1}"     && return
		[ -f "${root}/usr/lib/${1}" ] && file="${root}/usr/lib/${1}" && return
		[ -f "${root}/bin/${1}" ]     && file="${root}/bin/${1}"     && return
		[ -f "${root}/usr/bin/${1}" ] && file="${root}/usr/bin/${1}" && return
	fi
}

add_library() {
	local mode="$2"
	
	local file=""
	if [[ "$1" = :* ]] ; then
		find_file "${1#:}"
	elif [ "$mode" = "dynamic" ] ; then
		find_file "lib$1.so"
		find_file "lib$1.dll"
		find_file "lib$1.a"
	else
		find_file "lib$1.a"
		find_file "lib$1.so"
		find_file "lib$1.dll"
	fi
	
	[ -z "$file" ] && die "could not find -l$1"
	
	add_library_file "$file"
}

if [ "${compiler##*/}" = 'cl' ] || [ "${compiler##*/}" = 'link' ]
	then is_msvc=1
	else is_msvc=0
fi

# Parse and filter compiler parameters
is_search_path=0
is_library=0
mode="dynamic"
args=( )
for arg in "$@" ; do
	
	if [ $is_search_path = 1 ] ; then search_paths+=( "$arg" ) ; is_search_path=0 ; fi
	if [ $is_library = 1 ]     ; then add_library "$arg"       ; is_library=0     ; fi
	
	case "$arg" in
		
		# add library serach path
		-L|--library-path)    is_search_path=1                             ;;
		-L*)                  search_paths+=( "${arg#-L}" )                ;;
		--library-path=*)     search_paths+=( "${arg#--library-path=}" )   ;;
		
		/implib:*)                                                         ;;
		/out:*)                                                            ;;
		
		# add library dependency
		-l|--library)         is_library=1                                 ;;
		-l*)                  add_library      "${arg#-l}"         "$mode" ;;
		--library=*)          add_library      "${arg#--library=}" "$mode" ;;
		-Wl,--out-implib,*)   true                                         ;; # not a lib!
		-Wl,-soname,*)        true                                         ;; # not a lib!
		*.a|*.so|*.dll|*.lib) add_library_file "$arg"                      ;;
		
		# track static/dynamic library modes
		-Wl,-Bstatic)         mode="static"                                ;;
		-Wl,-Bdynamic)        mode="dynamic"                               ;;
		
		# add fake dependency if libstdc++ is used
		-static-libstdc++)    echo "${root}/libstdc++" >> "$depsfile"      ;;
		
		# filter flags
		-rdynamic)            continue                                     ;;
		
		-I*)              [ $is_msvc = 1 ] && add_library_file "${arg#-I}" ;;
		
	esac
	
	args+=( "$arg" )
done

# Collect used include files
if [ $is_msvc = 0 ] ; then
	localdepsfile="$(mktemp)"
	args+=(
		-MD -MF "$localdepsfile"
	)
fi

"$compiler" "${args[@]}"
status=$?

# Save used include files as dependencies
if [ $is_msvc = 0 ] ; then
	head -n1  "$localdepsfile" | sed "s/^.*: *//;s/ *\\\\\$//;s/ \$//" >> "$depsfile"
	tail -n+2 "$localdepsfile" | sed "s/^ *//;s/ *\\\\\$//"            >> "$depsfile"
	rm "$localdepsfile"
fi

exit $status
