#!/bin/bash

. "${BASH_SOURCE[0]%/*}/common"

if [ $is_snapshot = 0 ] ; then
	[ -z "$obs_project" ] && die
	_repodir="${builddir}/${project}.osc"
	_obs_project="$obs_project"
else
	[ -z "$obs_snapshot_project" ] && die
	_repodir="${builddir}/${project}-snapshots.osc"
	_obs_project="$obs_snapshot_project"
fi

if [ ! -e "$_repodir" ] ; then
	e osc checkout --output-dir="$_repodir" "$_obs_project" "$obs_package"
fi

pushd "$_repodir" > /dev/null

e osc update

mode=''
for arg in "$@" ; do
	
	if [ -z "$mode" ] ; then
		case "$arg" in
			-a|--add)             mode='add' ; continue ;;
			-d|-r|--del|--remove) mode='del' ; continue ;;
			--)                   mode='--'  ; continue ;;
			-*)                   die "uknown option ${arg}" ;;
		esac
	fi
	
	if [ "$mode" = 'del' ] ; then
		
		for f in "$_repodir"/* ; do
			name="${f##*/}"
			[[ "$name" == $arg ]] && e rm "$f"
		done
		
	else
		
		e cp "$arg" "$_repodir"/
		
	fi
	
	[ "$mode" = '--' ] || mode=''
done

e osc addremove

if [ $is_snapshot = 0 ]
	then e osc commit
	else e osc commit -m 'New development snapshot'
fi

popd > /dev/null
