#!/bin/bash

. "${BASH_SOURCE[0]%/*}/common"
. "${scriptdir}/changelog"

[ ! -z "${1-}" ] && pkgtype="$1"

mkdir -p "$builddir"
mkdir -p "$outdir"

elog "${white}packaging ${project}-${version}${reset}"

# Update source version and changelog data
make_changelog
runall update-version

# Build the source archive
run source build

# Build (portable) binary archives
runall build
runall test

# Send build jobs for Linux packages to the repective build servers
runall prepare
runall dispatch

# Sign archives and create checksum and readme files
runscript finalize

git status
