#!/bin/bash

. "${BASH_SOURCE[0]%/*}/common"
. "${scriptdir}/changelog"

[ ! -z "${1-}" ] && pkgtype="$1"

mkdir -p "$builddir"
mkdir -p "$outdir"

elog "${white}packaging ${project}-${version}${reset}"

# Update source version and changelog data
if [ $is_test_version = 0 ] && [ $is_snapshot = 0 ] ; then
	make_changelog
	runall update-version
fi

# Build the source archives
run source build
[ $is_test_version = 0 ] && [ $is_snapshot = 0 ] && runscript finalize

# Send build jobs for Linux packages to the repective build servers
if [ $is_test_version = 0 ] ; then
	if [ $is_snapshot = 0 ] \
	   || [ ! -z "${obs_snapshot_project:-}" ] || [ ! -z "${launchpad_snapshot_ppa:-}" ] ; then
		runall prepare
		runall dispatch
	fi
fi

# Build (portable) binary archives
runall build
runall test

# Sign archives and create checksum and readme files
runscript finalize

git status
