#!/bin/bash

. "${scriptdir}/changelog"

to_deb_version() {
	sed 's:\-\([a-z]\):~\1:g;s:\([a-z]\)\-:\1+:g'
}

if [ $is_snapshot = 0 ] ; then
	
	_deb_version="$(head -1 "${pkgsrcdir}/changelog" | sed 's/^.*(\([^\-]*\)-.*$/\1/')"
	echo "debian version is ${_deb_version}"
	_deb_release="$(head -1 "${pkgsrcdir}/changelog" | sed 's/^.*(\([^)]*\)).*$/\1/')"
	echo "debian release is ${_deb_release}"
	
	[ "$_deb_version" = "$version" ] || die "DEB version is ${_deb_version}, expected ${version}"
	
else
	
	_deb_version="$(printf '%s' "$version" | sed 's:\-\([a-z]\):~\1:g;s:\([a-z]\)\-:\1+:g')"
	echo "debian version is ${_deb_version}"
	_deb_release="${_deb_version}-0.1"
	echo "debian release is ${_deb_release}"
	
fi

_deb_bin_version="${_deb_version}+bin"
_deb_bin_release="${_deb_bin_version}${_deb_release#"$_deb_version"}"
