#!/bin/bash

. "${BASH_SOURCE[0]%/*}/../common"
. "${BASH_SOURCE[0]%/*}/common"

get_output _debsource _sourcedir "$version" "$pkgtype" 'prepare'

if [ $is_snapshot = 0 ] || [ ! -z "${obs_snapshot_project:-}" ] ; then
	
	e execute deploy-obs \
		--del "${project}*.dsc" \
		--del "${project}_*.orig.*" \
		--del "${project}_*.debian.*" \
		--add "${_debsource}/${project}_${_deb_release}.dsc" \
		--add "${_debsource}/${project}_${_deb_version}.orig".* \
		--add "${_debsource}/${project}_${_deb_release}.debian".*
	
fi

if [ $is_snapshot = 0 ] || [ ! -z "${launchpad_snapshot_ppa:-}" ] ; then
	
	if [ $is_snapshot = 0 ] ; then
		[ -z "$launchpad_ppa" ] && die
		_launchpad_ppa="$launchpad_ppa"
	else
		[ -z "$launchpad_snapshot_ppa" ] && die
		_launchpad_ppa="$launchpad_snapshot_ppa"
	fi
	
	for changes in "${_debsource}/${project}_${_deb_version}"-*ppa*~*_source.changes ; do
		e dput "$_launchpad_ppa" "$changes"
	done
	
fi
