#!/bin/bash

. "${BASH_SOURCE[0]%/*}/../common"

# Update our git repository to make sure we have the requested version if it exists
_repodir="${builddir}/${project}.git"
if [ ! -e "$_repodir" ] ; then
	e mkdir -p "$_repodir"
	if ! e git clone --mirror "$git_repository" "$_repodir" 2>&1 ; then
		erm -r "$_repodir"
		die "could not clone git repo at ${git_repository}"
	fi
fi
e git --git-dir="$_repodir" fetch --all 2>&1
e git --git-dir="$_repodir" fetch --tags 2>&1
e git --git-dir="$_repodir" remote prune origin 2>&1

# Create the source directory - name will be include in the source tarball
get_output _out _outdir
e mkdir "$_outdir"

# Checkout the source from git into our working directory
e git --git-dir="$_repodir" --work-tree="$_outdir" checkout "$commit" -f 2>&1
_git_log="$(git --git-dir="$_repodir" log -n1 --pretty=oneline "$commit")"
printf '  Using commit %s\n' "$_git_log" >&2

# Sanity check
[ -e "${_outdir}/.git" ] && die 'bad git, bad'

# Remove dotfiles
e find "$_outdir" -name '.*' -exec rm -rvf {} +

_version_file="${_outdir}/VERSION"
if [ -f "$_version_file" ] ; then
	if [ $is_test_version = 0 ] && [ $is_snapshot = 0 ] ; then
		# Check version number for stable releases
		_vername="$(head --lines=1 "$_version_file")"
		_version="${_vername##* }"
		[ "$version" = "$_version" ] || die "version file says ${_vername}"
		for changelog in "${_outdir}/"*CHANGELOG* ; do
			grep "$(escape_sed "$version")" "$changelog" > /dev/null \
				|| die "version ${version} not in ${changelog}"
		done
	else
		# Adjust version for test/patch releases
		_vername="$(head --lines=1 "$_version_file")"
		_commit="$(git --git-dir="$_repodir" rev-parse --short="$commit_prefix_length" "$commit")"
		if [[ "${version-}" == *.* ]] || [ $is_snapshot = 1 ] ; then
			_vername="${_vername% *} ${version} + ${_commit}"
		else
			if [ ! "$version" = "$commit" ] || [ ! "$version" = "$_commit" ] ; then
				_vername+="-${version}"
			fi
			if [ "$version" = "$commit" ] ; then
				_vername+=" + ${_commit}"
			fi
		fi
		_rest="$(tail -n+2 "$_version_file")"
		[ ! -z "$_rest" ] && _vername="$_vername
$_rest"
		echo "$_vername" > "$_version_file"
	fi
	if [ $flat_files_tree = 0 ] ; then
		git --git-dir="$_repodir" rev-parse "$commit" > "${_out%/*}/COMMIT"
		cp "$_version_file" "${_out%/*}/VERSION"
	fi
fi

function call_prepare_source() {
	
	local sourcedir="$_outdir"
	
	prepare_source
}
call_prepare_source

# Build the source tarball
e make_archive "$_out" "$_outdir" || die fail
